---
title: "hbs_qc"
output: html_document
date: "2025-07-30"
---

```{r setup, include=FALSE}
# renv::deactivate() 
# unlink("renv", recursive = TRUE, force = TRUE)  # deletes the renv/ folder
# unlink("renv.lock", force = TRUE)               # deletes the lockfile
# unlink(".Rprofile")


knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



Installing and Loading Packages

```{r}
# install.packages("devtools")
#devtools::install_github("michael-cw/SurveySolutionsAPIv2", build_vignettes = T)
# install.packages("ggplot2")
# install.packages("data.table")
# install.packages("raster")
# install.packages("sp")
# install.packages("leaflet")
# install.packages("rnaturalearth")
# install.packages("rnaturalearthdata")
# install.packages("sf")
# install.packages("exactextractr")
# install.packages("terra")



#load packages
library(SurveySolutionsAPIv2)
library(ggplot2)
library(data.table)
library(sp)
library(raster)
library(leaflet)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(terra)
library(exactextractr)
```



```{r pressure, echo=FALSE}
# Before setting key, make sure to generate a key in the server
suso_clear_keys()
suso_set_key("https://yemenhbs2025-2-demo.mysurvey.solutions", "api_cb", "yemenHBS2025!", "primary")
suso_keys()
```
Get Questionnaire List 

```{r # Checking questionnaire list in the workspace}
questlist <- suso_getQuestDetails()
print(questlist)

```

```{r}

#Export date = June 1 - July 8, 2025
data <- suso_export(
  server      = suso_get_api_key("susoServer"),
  apiUser     = suso_get_api_key("susoUser"),
  apiPass     = suso_get_api_key("susoPass"),
  token       = NULL,
  workspace   = suso_get_api_key("workspace"),
  questID     = questlist[4, QuestionnaireId],
  version     = 1,
  from_date   = "2025-07-01",
  from_time   = "00:00:00",
  to_date     = "2025-07-30",
  to_time     = "23:59:59",
  workStatus  = c("All", "SupervisorAssigned", "InterviewerAssigned",
                  "RejectedBySupervisor", "Completed", "ApprovedBySupervisor",
                  "RejectedByHeadquarters", "ApprovedByHeadquarters"),
  addTranslation        = FALSE,
  translationLanguage   = NULL,
  reloadTimeDiff        = 1,
  inShinyApp            = FALSE,
  verbose               = FALSE,
  weight_file           = NULL,
  process_mapquestions  = TRUE,
  combineFiles          = FALSE
)

```
